baseURL = "https://tylergray.dev"
disableAliases = true
enableRobotsTXT = false
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Tyler Gray"
description = "Here you will find writings, resources, and notes about technology, the web, etc."
summaryLength = 30

[imaging]
anchor = "smart"
quality = 90

[minify]
disableSVG = true

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[[menu.main]]
identifier = "resume"
name = "Résumé"
url = "/resume/"
weight = 3
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/jtgry"
weight = 4
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
      
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

[params]
disallow_search_engines = false

[related]
includeNewer = true
threshold = 80.0
toLower = true
[[related.indices]]
name = "description"
weight = 1
[[related.indices]]
name = "title"
weight = 2
[[related.indices]]
name = "tags"
weight = 3
